project:
  type: website
  output-dir: docs

website:
  title: "Gong Lab"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - people.qmd
      - research.qmd
      - publications.qmd
      - projects.qmd
      - news.qmd
      - join.qmd
      - contact.qmd

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true



